### PR TITLE
Patch For Threads

### LINKED ISSUE #553: bbi_args parallel=FALSE with no threads passed fails
# Summary

`bbi 1.4.0` (specifically #514) made the change that users no longer have to specify `parallel = TRUE` to have `submit_model()` respect the number passed the `threads`.

Unfortunately, it also introduced a bug where passing `parallel = FALSE` _without_ passing `threads` causes an error. 

# Example

You can reproduce this with the test suite model like so. _Note that you have to pass `threads = NULL` to reproduce with the test model because it already has `threads = 4` attached to the model object._

```r
MOD1 %>% submit_model(.bbi_args = list(parallel = F, threads = NULL))
# Error in if (.args$threads > 1 && isFALSE(.args$parallel)) warning("`threads > 1` but model will not run in parallel because `parallel = FALSE`") : 
#  missing value where TRUE/FALSE needed 
```

# Desired state

The user should be able to pass `submit_model(..., .bbi_args = list(parallel = FALSE))` to disable parallelization for that run.

### PR DESCRIPTION
**Pull request by rymarinelli**
Closes #553

### CODE REVIEW

**Comment by rymarinelli** [comment]
@seth127  I tried to add additional logic to address if threads is NULL. If threads is null, the handling present in ` check_bbi_args` will raise with a type error.  Since `NULL` is not a numeric, it will error here.  

```
    # check type
    if (ref$type == "character") {
      type_pass_bool <- is_bare_character(.v)
    } else if (ref$type == "logical") {
      type_pass_bool <- is_bare_logical(.v)
    } else if (ref$type == "numeric") {
      type_pass_bool <- is_bare_numeric(.v)
    } else {
      # This feels weird to put an intentional bug catch in here, but I don't like having to rely on raw string matching
      # from our aaa.R file to trigger functionality, so this feels like the safest option.
      stop(paste0("BUG!!! BBI_ARGS[['", .n, "']][['type']] is `", ref$type, "` which is invalid. 
     Must be either 'character', 'logical', or 'numeric'"))
```

File: tests/testthat/test-utils.R [hunk 1]
```diff
@@ -219,3 +219,36 @@ test_that("Confirms if threads = 1, parallel is not set [BBR-UTL-015]", {
...
+      purrr::walk(files_to_copy, fs::file_copy, file.path(tempdir(), "test_path"))
+      fs::dir_copy(file.path(ABS_MODEL_DIR, "1"), file.path(tempdir(), "test_path"))
+      ctl <- read_lines(file.path(tempdir(),"test_path", "1.ctl")) %>%  stringr::str_remove("../../../../extdata/")
+      write_lines(ctl, file.path(tempdir(),"test_path", "1.ctl"))
+
+      readr::write_file("threads:  ", file.path(tempdir(), "test_path", "bbi.yaml"))
+
+
+      mod1 <- new_model(file.path(tempdir(), "test_path", "1"), .description = "original test-workflow-bbi model",
+                        .bbi_args = list(parallel = FALSE, threads = NULL))
```
Comment (seth127) [inline tests/testthat/test-utils.R:244]: We shouldn't be testing passing `threads = NULL`, what we want to test is that user can pass `parallel = FALSE` _without_ passing threads at all, and then the test is that the `--parallel` flag _shouldn't_ show up in the `.dry_run` output.

**Comment by seth127** [comment]
Just noting on here that this comment above led to creating https://github.com/metrumresearchgroup/bbr/issues/555. I'm not sure if that needs to be addressed _before_ this PR or not, but it might.

File: R/utils.R [hunk 2]
```diff
@@ -74,6 +74,27 @@ check_bbi_args <- function(.args) {
...
+  }
+
+  else if(!is.null(.args$parallel) && is.null(.args$threads))
+  {
+    .args$parallel <- FALSE
+    cmd_args <- c(cmd_args, "--threads=1")
+
+  }
+
+  else if(is.null(.args$parallel) && is.null(.args$threads))
```
Comment (kyleam) [inline R/utils.R:91]: This condition is unreachable.  It's identical to the one on line 77.

File: R/utils.R [hunk 3]
```diff
@@ -74,6 +74,27 @@ check_bbi_args <- function(.args) {
     }
   }
   #If parallel is passed
+  else if(is.null(.args$parallel) && is.null(.args$threads))
```
Comment (kyleam) [inline R/utils.R:77]: I'm getting pretty turned around looking at this long chain of conditions.

```R
  #If parallel not passed
  if (is.null(.args$parallel) && !is.null(.args$threads))
  {
    if (.args$threads > 1)
    {
      cmd_args <- c(cmd_args, "--parallel")
    }
  }
  #If parallel is passed
  else if(is.null(.args$parallel) && is.null(.args$threads))
  {
    .args$parallel <- FALSE
    cmd_args <- c(cmd_args, "--threads=1")

  }

  else if(!is.null(.args$parallel) && is.null(.args$threads))
  {
    .args$parallel <- FALSE
    cmd_args <- c(cmd_args, "--threads=1")

  }

  else if(is.null(.args$parallel) && is.null(.args$threads))
  {
    .args$parallel <- FALSE
    cmd_args <- c(cmd_args, "--threads=1")

  }

  else{
    if (.args$threads > 1 &&
        isFALSE(.args$parallel))
      warning("`threads > 1` but model will not run in parallel because `parallel = FALSE`")
  }
```

 *  The "#If parallel is passed" comment is stale, I guess, because the condition right below it now includes `is.null(.args$parallel)`.

 * I'm surprised to see `args$parallel` being set to false.  That doesn't align with the desired behavior mentioned in https://github.com/metrumresearchgroup/bbr/issues/385#issuecomment-1182171875

---

Based on reading the desired behavior in <https://github.com/metrumresearchgroup/bbr/issues/385#issuecomment-1182171875>, it seems like the only time we should be doing anything is when threads is passed an above 1, so perhaps it makes sense to use that as the top condition?  Maybe the whole block above could be reduced to


```R
  if (!is.null(.args$threads) && .args$threads > 1) {
    if (is.null(.args$parallel)) {
      cmd_args <- c(cmd_args, "--parallel")
    } else if (isFALSE(.args$parallel)) {
      warning("`threads > 1` but model will not run in parallel because `parallel = FALSE`")
    }
  }
```

?

With that, a submit_models test would fail because it wouldn't match the `--threads=1` that you added in this PR's 4ce574d8, but I don't understand the reason for that change.

File: tests/testthat/test-utils.R [hunk 4]
```diff
@@ -219,3 +219,36 @@ test_that("Confirms if threads = 1, parallel is not set [BBR-UTL-015]", {
   })
 })
 
+test_that("confirms handling of default parameters [BBR-UTL-016]", {
+  withr::with_options(list(bbr.bbi_exe_path = read_bbi_path()),{
+    withr::with_tempdir({
```
Comment (kyleam) [inline tests/testthat/test-utils.R:224]: This looks like a good regression test.  I've confirmed that, if I revert the code changes, I get the failure from gh-553

I wonder whether we can simplify things a bit, making the core of the test stand out more.

Some notes:
  * `with_tempdir` puts you in a tempdir, so there is no need to create more tempdirs, use absolute paths, or clean up the directory afterword.
  * some of the model setup is unneeded for this test
  * if it's easy to avoid a warning, do so rather than suppressing it

I think this test could be reduced:

```R
test_that("confirms handling of default parameters [BBR-UTL-016]", {
  withr::with_tempdir({
    fs::file_copy(file.path(ABS_MODEL_DIR, "1.ctl"), ".")
    cat("", file = "bbi.yaml")
    mod1 <- new_model("1", .bbi_args = list(parallel = FALSE))
    res <- submit_model(mod1, .dry_run = TRUE)
    expect_false(all(str_detect(res$cmd_args, "--parallel")))
  })
})
```

Note that that triggers another bug in utils.R.  You could avoid it by adding another arg to `.bbi_args`, but I think it'd be better to fix it with something like this:

```diff
diff --git a/R/utils.R b/R/utils.R
index b858eacf..8fd8c86c 100644
--- a/R/utils.R
+++ b/R/utils.R
@@ -113,7 +113,13 @@ format_cmd_args <- function(.args, .collapse = FALSE) {
   if (.collapse) {
     return(paste0(arg_vec, collapse = " "))
   } else {
-    return(arg_vec %>% set_names(NULL))
+    res <- if (length(arg_vec) > 0) {
+      arg_vec %>% set_names(NULL)
+    } else {
+      arg_vec
+    }
+
+    return(res)
   }
 }
 
```

File: R/utils.R (hunk 3 above)
Comment (rymarinelli) [reply R/utils.R:77]: I think this makes sense. I was trying to think through all the combinations of what could be passed or not between parallel being set or not and threads.

**Comment by kyleam** [comment]
Hmm, that's a nasty error for the [mpn oldest/R4.0 check](https://github-drone.metrumrg.com/metrumresearchgroup/bbr/3280/2/4):

     *** caught segfault ***
    address 0x55be988d32d0, cause 'invalid permissions'

The [push build passed](https://github-drone.metrumrg.com/metrumresearchgroup/bbr/3279/2/4), so I'm not confident we're going to be able to retrigger and investigate that.

I'd suggest restarting the build (via the drone interface) to see whether it persists.

<details>
<summary>full log</summary>

```
+ R -s -e 'devtools::install_deps(upgrade = '"'"'never'"'"')'
Installing 1 packages: diffobj
Installing package into ‘/opt/rpkgs’
(as ‘lib’ is unspecified)
trying URL 'https://packagemanager.rstudio.com/all/__linux__/bionic/292/src/contrib/diffobj_0.3.0.tar.gz'
Content type 'binary/octet-stream' length 1000382 bytes (976 KB)
==================================================
downloaded 976 KB

* installing *binary* package ‘diffobj’ ...
* DONE (diffobj)

The downloaded source packages are in
    ‘/tmp/Rtmp4GMrEC/downloaded_packages’
+ R -s -e 'devtools::check(env_vars = c("BBI_EXE_PATH" = "/ephemeral/bbi", "NOT_CRAN" = "true"))'
Updating bbr documentation
Warning: Version of roxygen2 last used with this package is 7.2.1.  You only have version 7.1.0
Loading bbr
Writing NAMESPACE
Writing NAMESPACE
Writing create_bbi_object.Rd
Writing copy_model_from.Rd
Writing cov_cor.Rd
Writing get_based_on.Rd
Writing get_model_id.Rd
Writing get_data_path.Rd
Writing model_summaries.Rd
Writing as_summary_list.Rd
Writing model_summary.Rd
Writing modify_model_field.Rd
Writing modify_tags.Rd
Writing modify_notes.Rd
Writing modify_based_on.Rd
Writing modify_star.Rd
Writing modify_description.Rd
Writing modify_bbi_args.Rd
Writing verify_model_yaml_integrity.Rd
Writing nm_file.Rd
Writing nm_tables.Rd
Writing param_estimates_compare.Rd
Writing param_estimates.Rd
Writing param_labels.Rd
Writing print_bbi.Rd
Writing check_file.Rd
Writing check_output_dir.Rd
Writing check_nonmem_table_output.Rd
Writing plot_nonmem_table_df.Rd
Writing submit_model.Rd
Writing submit_models.Rd
Writing extract_from_summary.Rd
Writing wait_for_nonmem.Rd
── Building ───────────────────────────────────────────────────────────── bbr ──
Setting env vars:
● CFLAGS    : -Wall -pedantic
● CXXFLAGS  : -Wall -pedantic
● CXX11FLAGS: -Wall -pedantic
────────────────────────────────────────────────────────────────────────────────
  
   checking for file ‘/drone/src/DESCRIPTION’ ...
  
✔  checking for file ‘/drone/src/DESCRIPTION’

  
─  preparing ‘bbr’:

  
   checking DESCRIPTION meta-information ...
  
✔  checking DESCRIPTION meta-information

  
─  installing the package to build vignettes

  
   creating vignettes ...
  
✔  creating vignettes (19.4s)

  
─  checking for LF line-endings in source and make files and shell scripts

  
─  checking for empty or unneeded directories
   Removed empty directory ‘bbr/bbi_linux_amd64’

  
─  building ‘bbr_1.4.0.tar.gz’


── Checking ───────────────────────────────────────────────────────────── bbr ──
Setting env vars:
● _R_CHECK_CRAN_INCOMING_REMOTE_: FALSE
● _R_CHECK_CRAN_INCOMING_       : FALSE
● _R_CHECK_FORCE_SUGGESTS_      : FALSE
● BBI_EXE_PATH                  : /ephemeral/bbi
● NOT_CRAN                      : true
── R CMD check ─────────────────────────────────────────────────────────────────
* using log directory ‘/tmp/RtmpHuBw0K/bbr.Rcheck’
* using R version 4.0.3 (2020-10-10)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* using options ‘--no-manual --as-cran’
* checking for file ‘bbr/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘bbr’ version ‘1.4.0’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... NOTE
Packages suggested but not available for checking:
  'mrgvalidate', 'mrgvalprep'

Imports includes 21 non-default packages.
Importing from so many packages makes the package vulnerable to any of
them becoming unavailable.  Move as many as possible to Suggests and
use conditionally.
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘bbr’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking for future file timestamps ... OK
* checking ‘build’ directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... NOTE
Missing or unexported object: ‘cli::ansi_strwrap’
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat.R’ [36s/38s]
 ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  32: withRestarts(testthat_abort_reporter = function() NULL, force(code))
  33: with_reporter(reporter = reporter, start_end_reporter = start_end_reporter,     {        reporter$start_file(basename(path))        lister$start_file(basename(path))        source_file(path, new.env(parent = env), chdir = TRUE,             wrap = wrap)        reporter$.end_context()        reporter$end_file()    })
  34: FUN(X[[i]], ...)
  35: lapply(paths, test_file, env = env, reporter = current_reporter,     start_end_reporter = FALSE, load_helpers = FALSE, wrap = wrap)
  36: force(code)
  37: doWithOneRestart(return(expr), restart)
  38: withOneRestart(expr, restarts[[1L]])
  39: withRestarts(testthat_abort_reporter = function() NULL, force(code))
  40: with_reporter(reporter = current_reporter, results <- lapply(paths,     test_file, env = env, reporter = current_reporter, start_end_reporter = FALSE,     load_helpers = FALSE, wrap = wrap))
  41: test_files(paths, reporter = reporter, env = env, stop_on_failure = stop_on_failure,     stop_on_warning = stop_on_warning, wrap = wrap)
  42: test_dir(path = test_path, reporter = reporter, env = env, filter = filter,     ..., stop_on_failure = stop_on_failure, stop_on_warning = stop_on_warning,     wrap = wrap)
  43: test_package_dir(package = package, test_path = test_path, filter = filter,     reporter = reporter, ..., stop_on_failure = stop_on_failure,     stop_on_warning = stop_on_warning, wrap = wrap)
  44: test_check("bbr")
  An irrecoverable exception occurred. R is aborting now ...
  Segmentation fault (core dumped)
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking re-building of vignette outputs ... OK
* checking for non-standard things in the check directory ... OK
* checking for detritus in the temp directory ... OK
* DONE

Status: 1 ERROR, 2 NOTEs
See
  ‘/tmp/RtmpHuBw0K/bbr.Rcheck/00check.log’
for details.

── R CMD check results ────────────────────────────────────────── bbr 1.4.0 ────
Duration: 1m 59.7s

❯ checking tests ...
  See below...

❯ checking package dependencies ... NOTE
  Packages suggested but not available for checking:
    'mrgvalidate', 'mrgvalprep'

  Imports includes 21 non-default packages.
  Importing from so many packages makes the package vulnerable to any of
  them becoming unavailable.  Move as many as possible to Suggests and
  use conditionally.

❯ checking dependencies in R code ... NOTE
  Missing or unexported object: ‘cli::ansi_strwrap’

── Test failures ───────────────────────────────────────────────── testthat ────

> library(testthat)
> library(bbr)
>
> test_check("bbr")

 *** caught segfault ***
address 0x55be988d32d0, cause 'invalid permissions'

Traceback:
 1: dir_map(old, identity, all, recurse, type, fail)
 2: dir_ls(.base_dir, recurse = .recurse)
 3: find_models(.base_dir, .recurse, .include)
 4: summary_log(MODEL_DIR, .bbi_args = list(no_grd_file = TRUE))
 5: eval(code, test_env)
 6: eval(code, test_env)
 7: withCallingHandlers({    eval(code, test_env)    if (!handled && !is.null(test)) {        skip_empty()    }}, expectation = handle_expectation, skip = handle_skip, warning = handle_warning,     message = handle_message, error = handle_error)
 8: doTryCatch(return(expr), name, parentenv, handler)
 9: tryCatchOne(expr, names, parentenv, handlers[[1L]])
10: tryCatchList(expr, names[-nh], parentenv, handlers[-nh])
11: doTryCatch(return(expr), name, parentenv, handler)
12: tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]),     names[nh], parentenv, handlers[[nh]])
13: tryCatchList(expr, classes, parentenv, handlers)
14: tryCatch(withCallingHandlers({    eval(code, test_env)    if (!handled && !is.null(test)) {        skip_empty()    }}, expectation = handle_expectation, skip = handle_skip, warning = handle_warning,     message = handle_message, error = handle_error), error = handle_fatal,     skip = function(e) {    })
15: test_code(desc, code, env = parent.frame())
16: test_that("summary_log works some failed summaries [BBR-SMLG-008]",     {        clean_test_enviroment(create_all_models)        copy_all_output_dirs()        fs::file_delete(file.path(LEVEL2_MOD, "1.grd"))        sum_df <- summary_log(MODEL_DIR)        expect_equal(is.na(sum_df$error_msg), c(TRUE, TRUE, TRUE,             FALSE))        expect_equal(ncol(sum_df), SUM_LOG_COLS)        expect_equal(sum_df[[SL_FAIL_FLAGS]], c(FALSE, FALSE,             FALSE, FALSE))        sum_df <- summary_log(MODEL_DIR, .bbi_args = list(no_grd_file = TRUE))        test_sum_df(sum_df, c(MOD1_PATH, NEW_MOD2, NEW_MOD3,             LEVEL2_MOD), SUM_LOG_COLS)        fs::file_delete(file.path(NEW_MOD2, "2.ext"))        sum_df <- summary_log(MODEL_DIR, .bbi_args = list(no_grd_file = TRUE))        expect_equal(is.na(sum_df$error_msg), c(TRUE, FALSE,             TRUE, TRUE))        expect_equal(ncol(sum_df), SUM_LOG_COLS)        expect_equal(sum_df[[SL_FAIL_FLAGS]], c(FALSE, FALSE,             FALSE, FALSE))        sum_df <- summary_log(MODEL_DIR, .fail_flags = list(no_grd_file = TRUE))        expect_equal(is.na(sum_df$error_msg), c(TRUE, FALSE,             TRUE, TRUE))        expect_equal(ncol(sum_df), SUM_LOG_COLS)        expect_equal(sum_df[[SL_FAIL_FLAGS]], c(FALSE, FALSE,             FALSE, TRUE))    })
17: eval(code, test_env)
18: eval(code, test_env)
19: withCallingHandlers({    eval(code, test_env)    if (!handled && !is.null(test)) {        skip_empty()    }}, expectation = handle_expectation, skip = handle_skip, warning = handle_warning,     message = handle_message, error = handle_error)
20: doTryCatch(return(expr), name, parentenv, handler)
21: tryCatchOne(expr, names, parentenv, handlers[[1L]])
22: tryCatchList(expr, names[-nh], parentenv, handlers[-nh])
23: doTryCatch(return(expr), name, parentenv, handler)
24: tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]),     names[nh], parentenv, handlers[[nh]])
25: tryCatchList(expr, classes, parentenv, handlers)
26: tryCatch(withCallingHandlers({    eval(code, test_env)    if (!handled && !is.null(test)) {        skip_empty()    }}, expectation = handle_expectation, skip = handle_skip, warning = handle_warning,     message = handle_message, error = handle_error), error = handle_fatal,     skip = function(e) {    })
27: test_code(NULL, exprs, env)
28: source_file(path, new.env(parent = env), chdir = TRUE, wrap = wrap)
29: force(code)
30: doWithOneRestart(return(expr), restart)
31: withOneRestart(expr, restarts[[1L]])
32: withRestarts(testthat_abort_reporter = function() NULL, force(code))
33: with_reporter(reporter = reporter, start_end_reporter = start_end_reporter,     {        reporter$start_file(basename(path))        lister$start_file(basename(path))        source_file(path, new.env(parent = env), chdir = TRUE,             wrap = wrap)        reporter$.end_context()        reporter$end_file()    })
34: FUN(X[[i]], ...)
35: lapply(paths, test_file, env = env, reporter = current_reporter,     start_end_reporter = FALSE, load_helpers = FALSE, wrap = wrap)
36: force(code)
37: doWithOneRestart(return(expr), restart)
38: withOneRestart(expr, restarts[[1L]])
39: withRestarts(testthat_abort_reporter = function() NULL, force(code))
40: with_reporter(reporter = current_reporter, results <- lapply(paths,     test_file, env = env, reporter = current_reporter, start_end_reporter = FALSE,     load_helpers = FALSE, wrap = wrap))
41: test_files(paths, reporter = reporter, env = env, stop_on_failure = stop_on_failure,     stop_on_warning = stop_on_warning, wrap = wrap)
42: test_dir(path = test_path, reporter = reporter, env = env, filter = filter,     ..., stop_on_failure = stop_on_failure, stop_on_warning = stop_on_warning,     wrap = wrap)
43: test_package_dir(package = package, test_path = test_path, filter = filter,     reporter = reporter, ..., stop_on_failure = stop_on_failure,     stop_on_warning = stop_on_warning, wrap = wrap)
44: test_check("bbr")
An irrecoverable exception occurred. R is aborting now ...
Segmentation fault (core dumped)

1 error ✖ | 0 warnings ✔ | 2 notes ✖
Error: R CMD check found ERRORs
Execution halted
```

</details>

**Review by kyleam — APPROVED** [review]
@rymarinelli Thanks for the update.  I've confirmed again that, if I revert the `check_bbi_args ` changes, the test triggers the error from gh-553.  

Good to merge in my view.
